language: swift
osx_image: xcode10.2
install:
    - brew install danger/tap/danger-swift
script:
    - danger-swift ci
    - xcodebuild test -project JSONParse.xcodeproj -scheme JSONParse -destination 'os: osx'
after_success:
    - bash <(curl -s https://codecov.io/bash)
